const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function initNavigation(){const page=location.pathname.split('/').pop()||'index.html';$$('.site-nav a,.mobile-menu a').forEach(a=>{if(a.getAttribute('href')===page)a.classList.add('active')})}
function initMobileMenu(){const b=document.querySelector('.menu-toggle'),m=document.querySelector('.mobile-menu');if(!b||!m)return;const close=()=>{m.classList.remove('open');document.body.classList.remove('menu-open');b.setAttribute('aria-expanded','false')};b.onclick=()=>{const o=m.classList.toggle('open');document.body.classList.toggle('menu-open',o);b.setAttribute('aria-expanded',o)};$$('a',m).forEach(a=>a.onclick=close);document.addEventListener('keydown',e=>e.key==='Escape'&&close())}
function initHeaderScroll(){const h=document.querySelector('.site-header');addEventListener('scroll',()=>h?.classList.toggle('compact',scrollY>40),{passive:true})}
function initScrollReveal(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.12});$$('.reveal,.image-reveal').forEach(e=>o.observe(e))}
function initCounters(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const n=e.target,target=+n.dataset.count,start=performance.now(),dur=1200;requestAnimationFrame(function tick(t){const p=Math.min((t-start)/dur,1);n.textContent=Math.floor(target*(1-Math.pow(1-p,3)))+(n.dataset.plus||'');if(p<1)requestAnimationFrame(tick)});o.unobserve(n)}),{threshold:.5});$$('[data-count]').forEach(n=>o.observe(n))}
function initAnniversaryCounter(){const n=document.querySelector('[data-anniversary]');if(!n)return;const start=new Date('2017-09-01T00:00:00'),now=new Date();let y=now.getFullYear()-start.getFullYear(),m=now.getMonth()-start.getMonth(),d=now.getDate()-start.getDate();if(d<0){m--;d+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}n.textContent=`${y} лет · ${m} мес. · ${d} дн.`}
function initGallery(){}
function initLightbox(){const items=$$('.gallery button');if(!items.length)return;const l=document.querySelector('.lightbox'),im=l.querySelector('img'),close=l.querySelector('.close');let i=0;const show=x=>{i=(x+items.length)%items.length;im.src=items[i].querySelector('img').src;l.classList.add('open');l.setAttribute('aria-hidden','false')};items.forEach((x,j)=>x.onclick=()=>show(j));close.onclick=()=>l.classList.remove('open');l.onclick=e=>{if(e.target===l)close.click()};l.querySelector('.prev').onclick=()=>show(i-1);l.querySelector('.next').onclick=()=>show(i+1);document.addEventListener('keydown',e=>{if(!l.classList.contains('open'))return;if(e.key==='Escape')close.click();if(e.key==='ArrowRight')show(i+1);if(e.key==='ArrowLeft')show(i-1)})}
function initPageTransitions(){$$('a[href$=".html"]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||a.target)return;e.preventDefault();document.body.classList.add('is-leaving');setTimeout(()=>location=a.href,440)}))}
function initImageFallbacks(){$$('img').forEach(i=>i.addEventListener('error',()=>{const p=document.createElement('div');p.className='image-placeholder';p.style.display='grid';i.parentElement.replaceWith(p);console.warn('Image failed:',i.src)},{once:true}))}
function initInteractiveStories(){$$('.story').forEach(s=>{s.onclick=()=>{$$('.story').forEach(x=>x.classList.remove('active'));s.classList.add('active')}})}
function initParallax(){const el=$$('[data-parallax]');if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;addEventListener('scroll',()=>el.forEach(x=>x.style.transform=`translateY(${(innerHeight-x.getBoundingClientRect().top)*.035}px)`),{passive:true})}
document.addEventListener('DOMContentLoaded',()=>{initNavigation();initMobileMenu();initHeaderScroll();initScrollReveal();initCounters();initAnniversaryCounter();initGallery();initLightbox();initPageTransitions();initImageFallbacks();initInteractiveStories();initParallax()});
