import {club,philosophy,stories} from './data/club.js';import {coach} from './data/coach.js';import {stats} from './data/achievements.js';import {athletes} from './data/athletes.js';import {events} from './data/events.js';import {media} from './data/media.js';
const nav=[['/','Главная'],['/about','О клубе'],['/coach','Тренер'],['/athletes','Спортсмены'],['/achievements','Достижения'],['/events','События'],['/gallery','Галерея'],['/club-life','Жизнь клуба'],['/history','История'],['/contacts','Контакты']];
const img=(src:string,alt:string,ratio='4 / 5',cap='')=>`<figure class="premium-image" style="aspect-ratio:${ratio}"><img src="${src}" alt="${alt}" loading="lazy" decoding="async" onerror="this.parentElement.classList.add('missing');this.remove()"><div class="image-fallback" role="img" aria-label="${alt}"><span>${alt.split(' ').map(w=>w[0]).join('').slice(0,4)}</span><b>Фото ожидается</b><small>${src}</small></div>${cap?`<figcaption>${cap}</figcaption>`:''}</figure>`;
const title=(k:string,t:string)=>`<div class="section-title"><span>${k}</span><h2>${t}</h2></div>`;const finalHero=()=>`<section class="final"><h2>МАКСИМА<br>НА МАКСИМУМ</h2><p>01.09.2017 — 01.09.2026 · 9 ЛЕТ</p><p>${club.tagline}</p><em>И это только начало.</em></section>`;
const statsGrid=()=>`<section class="dark">${title('03 / архив результата','Цифры сезона')}<div class="stats-grid">${stats.map(([v,l])=>`<div class="stat" data-value="${parseInt(v)}" data-plus="${v.includes('+')}"><b>0</b><span>${l}</span></div>`).join('')}</div></section>`;
const anniversary=()=>{const now=new Date(),start=new Date(club.founded);let m=(now.getFullYear()-start.getFullYear())*12+now.getMonth()-start.getMonth();if(now.getDate()<start.getDate())m--;return`<section class="anniversary"><div class="huge">9 ЛЕТ</div><div class="date-stack"><span>01.09.2017</span><i></i><span>01.09.2026</span></div><div class="live-count"><b>${Math.floor(m/12)}</b><span>лет</span><b>${m}</b><span>месяцев</span><b>${Math.floor((+now-+start)/86400000)}</b><span>дней</span></div></section>`};
const storiesBlock=()=>`<section>${title('09 / интерактив','9 историй')}<div class="stories">${stories.map((s,i)=>`<button class="${i==0?'active':''}"><span>${String(i+1).padStart(2,'0')}</span>${s}</button>`).join('')}</div></section>`;
const feature=()=>{const best=athletes.find(a=>a.slug==='dubovik-patskova')!,solo=athletes.find(a=>a.slug==='mozol-alexandra')!;return`<section class="feature">${img(best.image,best.name,'4 / 5','BEST COUPLE / 2025—2026')}<div><span class="eyebrow">${best.seasonAward}</span><h2>${best.name}</h2><ul>${best.achievements.map(x=>`<li>${x}</li>`).join('')}</ul></div></section><section class="feature reverse">${img(solo.image,solo.name,'3 / 4','SOLOIST / 2025—2026')}<div><span class="eyebrow">${solo.seasonAward}</span><h2>${solo.name}</h2><ul>${solo.achievements.map(x=>`<li>${x}</li>`).join('')}</ul></div></section>`};
const home=()=>`<section class="hero"><div class="intro"><span>2017 ↓ 2026 ↓ 09</span><button>Пропустить</button><b>${club.motto}</b></div><div class="hero-copy"><p>${club.name} · Танцевально-спортивный клуб. Минск.</p><h1>МАКСИМА<br><em>НА МАКСИМУМ</em></h1><span>01 / 09 / 2017 — 2026</span></div>${img(media.hero.main,'ТСК Максима hero','16 / 10','ANNIVERSARY DIGITAL EXPERIENCE')}</section>${anniversary()}<section class="feature"><div><span class="eyebrow">Основатель</span><h2>${coach.name}</h2><p>Мастер спорта Республики Беларусь по танцевальному спорту, педагог первой квалификационной категории и главный тренер клуба.</p></div>${img(media.coach.portrait,coach.name,'3 / 4')}</section>${feature()}${statsGrid()}<section class="event-card"><span>Ближайшее событие</span><h2>${events[0].title}</h2><p>${events[0].date}</p></section>${storiesBlock()}${finalHero()}`;
const pages:Record<string,()=>string>={
'/':home,'/about':()=>`<section class="page-hero"><span>01 / клуб</span><h1>О КЛУБЕ</h1><p>ТСК «Мáксима» — это место, где любовь к движению перерастает в высокие спортивные результаты.</p></section><section class="editorial"><p>Клуб специализируется на спортивных бальных танцах: европейская и латиноамериканская программы.</p>${title('философия','Не просто научить танцевать')}<div class="pill-grid">${philosophy.map(x=>`<span>${x}</span>`).join('')}</div></section>${statsGrid()}${finalHero()}`,
'/coach':()=>`<section class="page-hero coach-hero"><div><span>02 / главный тренер</span><h1>${coach.name}</h1><p>${coach.role}</p></div>${img(media.coach.portrait,coach.name,'3 / 4')}</section><section class="regalia">${coach.regalia.map(r=>`<p>${r}</p>`).join('')}</section><section class="path">${coach.path.map((p,i)=>`<button><b>${String(i+1).padStart(2,'0')}</b>${p}</button>`).join('')}</section><section class="cards-three">${coach.philosophy.map(([t,d])=>`<article><h2>${t}</h2><p>${d}</p></article>`).join('')}</section>${finalHero()}`,
'/athletes':()=>`<section class="page-hero"><span>03 / команда</span><h1>НАША ГОРДОСТЬ</h1><p>Пары, солисты, ансамбли и формейшн — современное поколение ТСК «Мáксима».</p></section><div class="filters">${['Все','Пары','Солисты','Ансамбли','Формейшн'].map(x=>`<button data-filter="${x}" class="${x==='Все'?'active':''}">${x}</button>`).join('')}</div><section class="athlete-grid">${athletes.map(a=>`<details class="athlete-card" data-type="${a.type}"><summary>${img(a.image,a.name,'4 / 5')}<span>${a.type} · ${a.category}</span><h2>${a.name}</h2>${a.seasonAward?`<b>${a.seasonAward}</b>`:''}</summary><ul>${a.achievements.map(x=>`<li>${x}</li>`).join('')}</ul>${a.members?`<p>Участники: ${a.members.join(', ')}.</p>`:''}</details>`).join('')}</section>`,
'/achievements':()=>`<section class="page-hero"><span>04 / data archive</span><h1>ДОСТИЖЕНИЯ</h1><p>Большие числа, финалы, медали и турниры — собранные как editorial archive.</p></section>${statsGrid()}<section class="medal-line"><b>23</b><span>золото</span><b>22</b><span>серебро</span><b>22</b><span>бронза</span></section>${storiesBlock()}`,
'/events':()=>`<section class="page-hero"><span>05 / calendar</span><h1>СОБЫТИЯ</h1></section><section class="event-card"><span>${events[0].kind}</span><h2>${events[0].title}</h2><p>${events[0].date}</p><small>${events[0].description}</small></section>`,
'/gallery':()=>`<section class="page-hero"><span>06 / visual archive</span><h1>ГАЛЕРЕЯ</h1><p>Editorial gallery с ожидаемыми путями для будущих фотографий.</p></section><section class="masonry">${[media.coach.dance,media.coach.univers,media.couples.dubovikPatskova.hero,media.soloists.mozolAlexandra.hero,media.ensembles.gonshchicy.hero,media.ensembles.lazurit.hero].map((s,i)=>`<button class="gallery-open">${img(s,`Галерея ${i+1}`,i%3===0?'16 / 10':'4 / 5',['training','competition','awards','team','backstage','portrait'][i])}</button>`).join('')}</section>`,
'/club-life':()=>`<section class="page-hero"><span>07 / documentary</span><h1>ЖИЗНЬ КЛУБА</h1><p>Premium documentary о тренировках, соревнованиях, награждениях и команде — без выдуманных историй.</p></section><section class="documentary">${[['/images/training/session-01.jpg','тренировки'],['/images/competitions/floor-01.jpg','соревнования'],['/images/awards/podium-01.jpg','награждения'],['/images/club/team-01.jpg','команда'],['/images/club/backstage-01.jpg','backstage']].map(([s,c],i)=>`<article>${img(s,c,i%2?'4 / 5':'16 / 9',c)}<h2>${c}</h2></article>`).join('')}</section>`,
'/history':()=>`<section class="page-hero"><span>08 / timeline</span><h1>01.09.2017</h1><p>История клуба через подтверждённые факты.</p></section><section class="timeline">${['основание клуба 01.09.2017','путь Максима из «Дуэта»','участие в «Univers»','спортивные достижения','развитие клуба','первые кубки','современное поколение спортсменов','сезон 2025/2026','9 лет в 2026 году'].map((h,i)=>`<article><b>${String(i+1).padStart(2,'0')}</b><p>${h}</p></article>`).join('')}</section>${storiesBlock()}${finalHero()}`,
'/contacts':()=>`<section class="page-hero"><span>09 / Минск</span><h1>КОНТАКТЫ</h1><p>${club.name}</p></section><section class="contacts"><h2>Минск</h2>${club.address.map(x=>`<p>${x}</p>`).join('')}<a href="tel:${club.phone.replaceAll(' ','')}">${club.phone}</a></section>`};
function render(){document.getElementById('root')!.innerHTML=`<header class="site-header"><a class="brand" href="/"><span class="logo-mark">09</span><span>${club.name}<small>${club.motto}</small></span></a><nav class="desktop-nav">${nav.map(([h,l])=>`<a class="${location.pathname===h?'active':''}" href="${h}">${l}</a>`).join('')}</nav><div class="anniv">2017—2026</div><button class="menu-btn" aria-expanded="false">Меню</button></header><div class="mobile-menu">${nav.map(([h,l])=>`<a href="${h}">${l}</a>`).join('')}</div><main class="page-transition">${(pages[location.pathname]??home)()}</main><footer><div><b>${club.name}</b><p>${club.motto}</p></div><strong>2017 — 2026</strong><p>${club.tagline}</p></footer>`;wire()}
function wire(){document.querySelector('.menu-btn')?.addEventListener('click',e=>{const menu=document.querySelector('.mobile-menu')!,btn=e.currentTarget as HTMLButtonElement;menu.classList.toggle('open');btn.ariaExpanded=String(menu.classList.contains('open'))});addEventListener('scroll',()=>document.querySelector('.site-header')?.classList.toggle('compact',scrollY>30),{passive:true});document.querySelector('.intro button')?.addEventListener('click',()=>document.querySelector('.intro')?.remove());document.querySelectorAll('.stories button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.stories button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));document.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll<HTMLElement>('.athlete-card').forEach(c=>c.hidden=b.dataset.filter!=='Все'&&c.dataset.type!==b.dataset.filter)}));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const el=e.target as HTMLElement,n=Number(el.dataset.value),plus=el.dataset.plus==='true',out=el.querySelector('b')!;let v=0;const id=setInterval(()=>{v+=Math.max(1,Math.ceil(n/45));out.textContent=`${Math.min(v,n)}${plus?' +':''}`;if(v>=n)clearInterval(id)},26);io.unobserve(el)}}),{threshold:.35});document.querySelectorAll<HTMLElement>('.stat').forEach(s=>io.observe(s))}
render();
